### ISSUE TITLE
The unikernel never terminates when the main terminates on `uk_sched_thread_exit`

### ISSUE THREAD

**Issue by shym** [unikraft/unikraft#1493]
### Describe the bug

When the main thread ends on `uk_sched_thread_exit`, the unikernel never stops as the idle thread gets constantly rescheduled.

### Steps to reproduce

Running the following simple unikernel:

```c
extern void uk_sched_thread_exit(void);

int main() {
  uk_sched_thread_exit();
  return 0;
}
```

with the simple configuration:

```yaml
# Kraftfile
spec: v0.6
name: bug
unikraft: staging
targets:
- qemu/x86_64
```

and

```make
# Makefile.uk
$(eval $(call addlib,appbug))

APPBUG_SRCS-y += $(APPBUG_BASE)/main.c
```

When `kraft build && kraft run`-ing, QEMU gets stuck.

### Expected behavior

The unikernel should just stop when all the threads end.
