### ISSUE TITLE
Build warning in `lib/vfscore/stdio.c`

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#544]
### Describe the bug

When using [`lib-newlib`](https://github.com/unikraft/lib-newlib) there is a build warning around `dup2` system call.

**Hackathon points**: 15

### Steps to reproduce

Add `newlibc` dependency to your build. This is a sample `kraft.yaml` config for this:

```
---
specification: '0.5'
name: helloworld
unikraft:
  version: 0.10.0
targets:
  - architecture: x86_64
    platform: linuxu
  - architecture: x86_64
    platform: kvm
  - architecture: x86_64
    platform: xen
  - architecture: arm64
    platform: linuxu
  - architecture: arm64
    platform: kvm
  - architecture: arm
    platform: linuxu
libraries:
  newlib:
    version: 0.10.0
    kconfig:
      - CONFIG_LIBNEWLIBC=y
```

### Expected behavior

There should be no build warnings.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
/home/razvan/usoc/unikraft/lib/vfscore/stdio.c: In function ‘init_stdio’:
/home/razvan/usoc/unikraft/lib/vfscore/stdio.c:221:6: warning: implicit declaration of function ‘uk_syscall_r_dup2’; did you mean ‘uk_syscall_r_stub’? [-Wimplicit-function-declaration
]                                                                      
  if (uk_syscall_r_dup2(0, 1) != 1)                                           
      ^~~~~~~~~~~~~~~~~                                                
      uk_syscall_r_stub  
```
