### ISSUE TITLE
`ioctl` build warning in `lib/vfscore/main.c`

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#548]
### Describe the bug

When using [`lib-newlib`](https://github.com/unikraft/lib-newlib) there is a build warning around `ioctl` system call.

**Hackathon points**: 20

### Steps to reproduce

Add `newlibc` dependency to your build. This is a sample `kraft.yaml` config for this:

```
---
specification: '0.5'
name: helloworld
unikraft:
  version: 0.10.0
targets:
  - architecture: x86_64
    platform: linuxu
  - architecture: x86_64
    platform: kvm
  - architecture: x86_64
    platform: xen
  - architecture: arm64
    platform: linuxu
  - architecture: arm64
    platform: kvm
  - architecture: arm
    platform: linuxu
libraries:
  newlib:
    version: 0.10.0
    kconfig:
      - CONFIG_LIBNEWLIBC=y
```

### Expected behavior

There should be no build warnings.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
/home/razvan/.unikraft/unikraft/lib/vfscore/main.c: In function ‘ioctl’:               
/home/razvan/.unikraft/unikraft/lib/vfscore/main.c:686:41: warning: passing argument 3 of ‘uk_syscall_e_ioctl’ makes integer from pointer without a cast [-Wint-conversion]
  return uk_syscall_e_ioctl(fd, request, arg);
```
