### ISSUE TITLE
`sync` build warning in `lib/vfscore/mount.c`

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#549]
### Describe the bug

When using [`lib-newlib`](https://github.com/unikraft/lib-newlib) there is a build warning around `sync` system call.

**Hackathon points**: 20

### Steps to reproduce

Add `newlibc` dependency to your build. This is a sample `kraft.yaml` config for this:

```
---
specification: '0.5'
name: helloworld
unikraft:
  version: 0.10.0
targets:
  - architecture: x86_64
    platform: linuxu
  - architecture: x86_64
    platform: kvm
  - architecture: x86_64
    platform: xen
  - architecture: arm64
    platform: linuxu
  - architecture: arm64
    platform: kvm
  - architecture: arm
    platform: linuxu
libraries:
  newlib:
    version: 0.10.0
    kconfig:
      - CONFIG_LIBNEWLIBC=y
```

### Expected behavior

There should be no build warnings.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
/home/razvan/.unikraft/unikraft/lib/vfscore/mount.c: In function ‘__uk_syscall_r_sync’:
/home/razvan/.unikraft/unikraft/lib/vfscore/mount.c:380:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
```
